### ISSUE TITLE
Node not working in a Windows 11 System

### ISSUE THREAD

**Issue by BlackVortexAI** [shinich39/comfyui-load-image-in-seq#4]
Not working through on error after another.

OS: Windows 11

Default Save Node from ComfyUI filename "ComfyUI_00001.png". Try to load the file with a period.

got prompt
!!! Exception during processing !!! [Errno 2] No such file or directory: 'X:\\StabilityMatrix\\Images\\Text2Img\\Render\\.ComfyUI_00001.png'
Traceback (most recent call last):
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "X:\StabilityMatrix\Packages\ComfyUI\custom_nodes\comfyui-load-image-in-seq\__init__.py", line 184, in exec
    image = Image.open(mask_path)
  File "X:\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\StabilityMatrix\\Images\\Text2Img\\Render\\.ComfyUI_00001.png'

If i Change the filename to the period version. ":ComfyUI_00001.png" another error occurs:

!!! Exception during processing !!! integer division or modulo by zero
Traceback (most recent call last):
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "X:\StabilityMatrix\Packages\ComfyUI\custom_nodes\comfyui-load-image-in-seq\__init__.py", line 179, in exec
    file_path = file_list[(index + len(file_list)) % len(file_list)]
ZeroDivisionError: integer division or modulo by zero

**Comment by shinich39** [comment]
I did fix it. 
Load original image when mask image deleted.
This node has a terrible masking process :(
